

USE NORTHWND;

--AND
SELECT * FROM Customers;

--MOSTRAR LOS CLIENTES QUE SON DE BRAZIL Y DE RIO DE JANEIRO

SELECT * FROM Customers
WHERE Country ='Brazil' AND City = 'Rio de Janeiro';

--MOSTRAR LOS PRODUCTOS DONDE EL PRECIO SEA MAYOR A 40 Y EL STOCK SEA MENOR O IGUAL A 20
--ORDENARLO DE MANERA ASCENDENTE POR EL PRECIO Y EL STOCK


SELECT * FROM Products;

SELECT * FROM Products
WHERE UnitPrice > 40 AND UnitsInStock <=20
ORDER BY UnitPrice,UnitsInStock ASC;

--OR
SELECT * FROM Customers;

--MOSTRAR LOS CLIENTES QUE SON DE BRAZIL O ARGENTINA

SELECT * FROM Customers
WHERE Country ='Brazil' OR Country = 'Argentina'
ORDER BY Country;

--MOSTRAR LOS CLIENTES DE FRANCIA O PERU

SELECT * FROM Customers
WHERE Country ='France' OR Country = 'Peru'
ORDER BY Country;


--PARENTESIS--MOSTRAR LOS CLIENTES QUE SON DE PARIS FRANCIA Y LA CIUDAD DE PARIS O EL PAIS DE AUTRIA

SELECT * FROM Customers
WHERE Country ='France' AND City = 'Paris' OR Country = 'Austria'
ORDER BY Country,City;

SELECT * FROM Customers
WHERE Country ='France' AND (City = 'Paris' OR Country = 'Austria')
ORDER BY Country,City;

SELECT * FROM Customers
WHERE City = 'Paris' OR Country = 'Austria'
ORDER BY Country,City;


--MOSTRAR LOS PRODUCTOS DONDE EL PRECIO SEA MAYOR A 100 O MENOR A 9
--ORDENANDO DE MANERA DESCENDENTE POR EL PRECIO

SELECT * FROM Products;


SELECT * FROM Products
WHERE UnitPrice > 100 OR UnitPrice < 9
ORDER BY UnitPrice DESC;

--IN
--MOSTRAR LOS CLIENTES QUE SEAN DE LA CIUDAD DE SAO PAULO,MADRID,LISBOA,O TOKIO

SELECT * FROM Customers;

SELECT * FROM Customers
WHERE City IN ('Sao Paulo','Madrid','Lisboa','Tokio')
ORDER BY City;

--MOSTRAR LOS PRODUCTOS DONDE EL PRECIO SEA 10,20,30,40 ORDENADO DE MANERA ASCENDENTE POR EL PRECIO

SELECT * FROM Products;

SELECT * FROM Products
WHERE UnitPrice IN (10,20,30,40)
ORDER BY UnitPrice ASC ;


--LIKE

SELECT * FROM Customers
ORDER BY ContactName;

--COMPARACION EXACTA =
SELECT * FROM Customers
WHERE ContactName = 'Ana Trujillo';


SELECT * FROM Customers
WHERE ContactName LIKE 'Ana Trujillo';


--CONSULTAR LOS DATOS DE LA TABLA CLIENTES DONDE EL NOMBRE DEL CONTACTO INICIE CON EL NOMBRE 
--CARLOS ORDENADO CON NOMBRE DE CONTACTO

SELECT * FROM Customers
WHERE ContactName LIKE 'Carlos%'
ORDER BY ContactName;

--CONSULTAR LOS DATOS DE LA TABLA CLIENTES DONDE EL CARGO(CONTACT TITLE) TERMINE CON LA PALABRA MANAGER
--ORDENADO NOMBRE CONTACTO

SELECT * FROM Customers
WHERE ContactTitle LIKE '%Manager'
ORDER BY ContactTitle;


--CONSULTAR LOS DATOS DE LA TABLA CLIENTES DONDE EL CONTACTO(CONTACT NAME) CONTENGA LA PALABRA PEDRO
--ORDENADO NOMBRE CONTACTO

SELECT * FROM Customers
WHERE ContactName LIKE '%Pedro%'
ORDER BY ContactName;

--CARACTERES ESPECIALES

SELECT * FROM Customers
WHERE ContactName = 'Carlos González'
ORDER BY ContactName;

SELECT * FROM Customers
WHERE ContactName = '%Gonz_lez'
ORDER BY ContactName;

SELECT * FROM Customers
WHERE ContactName LIKE '%Gonz_lez'
ORDER BY ContactName;

SELECT * FROM Customers
WHERE ContactName LIKE '%Gonz_le_'
ORDER BY ContactName;


--MOSTRAR LOS CLIENTES DONDE LA DIRECCION CONTENGA AVENIDAS AV.

SELECT * FROM Customers
WHERE Address LIKE '%AV_%';

SELECT * FROM Customers
WHERE Address LIKE '%AV.%';

--MOSTRAR LOS CLIENTES DONDE EL TELEFONO INICE CON 3 NUEMROS SEGUIDOS LUEGO EL GUION
--Y LOS NUMEROS RESTANTES.

SELECT * FROM Customers
WHERE Phone LIKE '___-%';


--BETWEEN

--CONSULTAR LOS PRODUCTOS DONDE EL PRECIO SE ENCUENTRE EN EL RANGO 10 HASTA 20
--ORDENAR DE MANERA ASCENDENTE POR PRECIO

SELECT * FROM Products;

SELECT * FROM Products
WHERE UnitPrice BETWEEN 10 AND 20
ORDER BY UnitPrice;

--CONSULTAR LOS DATOS DE LA TABLA PEDIDOS DONDE LA FECHA DE ORDEN SE ENCUENTRE EN EL RANGO 01/09/1996 HASTA 31/10/1996
--ORDENAR DE MANERA ASCENDENTE POR LA FECHA DE ORDEN

SELECT * FROM Orders;

--AÑOS MES Y DIA

SELECT * FROM Orders
WHERE OrderDate BETWEEN '19960901' AND '19961031'
ORDER BY OrderDate;


SELECT * FROM Orders
WHERE OrderDate BETWEEN '1996-09-01' AND '1996-10-31'
ORDER BY OrderDate;

SELECT * FROM Orders
WHERE OrderDate BETWEEN '1996/09/01' AND '1996/10/31'
ORDER BY OrderDate;

SET DATEFORMAT ymd;


--ONSULTAR LOS DATOS DE LA TABLA PEDIDOS DONDE EL PAIS DE NEVIO SE ENCUENTRE EN EL RANGO DE ALEMANIA
--HASTA MEXICO ORDENAR DE MANERA ASCENDENTE POR EL PAIS DE ENVIO



SELECT * FROM Orders;

SELECT * FROM Orders
WHERE ShipCountry BETWEEN 'Germany' AND 'Mexico'
ORDER BY ShipCountry;

--MOSTRAR LOS DATOS DE LA TABLA PRODUCTOS DONDE EL STOCK SE ENCUENTRE EN EL RANGO DE
--20 HASTA 30 ORDENAR DE MANERA ASCENDENTE POR EL STOCK

SELECT * FROM Products;

SELECT * FROM Products
WHERE UnitsInStock BETWEEN 20 AND 30
ORDER BY UnitsInStock;

--CONSULTAR LOS DATOS DE LA TABLA PEDIDOS DONDE LA FECHA DE ENVIO SE ENCUENTRE EN EL RANGO 01/01/1998 HASTA 01/03/1998
--ORDENAR DE MANERA ASCENDENTE POR LA FECHA DE ENVIO

SELECT * FROM Orders;

SELECT * FROM Orders
WHERE ShippedDate BETWEEN '1998-01-01' AND '1998-03-01'
ORDER BY ShippedDate;


--NOT

--CONSULTAR LOS EMPLEADOS QUE NO SEAN DE USA

SELECT * FROM Employees
WHERE NOT Country = 'USA';


--CONSULTAR LOS CLIENTES QUE NO SEAN DE USA, SPAIN, FRANCE Y BRAZIL 
--ORDENAR DE MANERA ASCENDENTE POR PAIS

SELECT * FROM Customers;

SELECT * FROM Customers
WHERE NOT Country IN ('USA','France','Spain','Brazil')
ORDER BY Country;


--MOSTRAR LOS DATOS DE LA TABLA PRODUCTOS DONDE EL STOCK NO SEA MAYOR O IGUAL A 20 ORDENAR
--DE MANERA DESCENDENTE POR EL STOCK

SELECT * FROM Products;

SELECT * FROM Products
WHERE NOT UnitsInStock >= 20
ORDER BY UnitsInStock DESC;

--MOSTRAR LOS CLIENTES DONDE EL TELEFONO NO INICIE POR ABRIR PARENTESIS

SELECT * FROM Customers;

SELECT * FROM Customers
WHERE NOT PHONE LIKE '(%';


--PUBS

USE pubs;

--MOSTRAR LOS AUTORES QUE SEAN DEL ESTADO CA Y LA CIUDAD DE PALO ALTO

SELECT * FROM authors
WHERE state = 'CA' AND city = 'Palo Alto';


--MOSTRAR LOS TITULOS DONDE EL PRECIO SEA MAYOR O IGUAL A 20 O MENOR O IGUAL A 7.

SELECT * FROM titles
WHERE price >= 20 OR price <= 7 ;


--MOSTRAR TODOS LOS EMPLEADOS DONDE EL NOMBRE INICIE CON LA LETRA M

SELECT * FROM employee
WHERE fname LIKE 'M%';


--MOSTRAR LOS AUTORES QUE SEAN DEL ESTADO DE MD,IN,OR

SELECT * FROM authors
WHERE state IN ('MD','IN','OR');
