

USE NORTHWND;

SELECT * FROM Products;

--SUMA Y RESTA

--CONSULTAR EL NOMBRE Y PRECIO DE LOS PRODUCTOS 
--AUMENTAR EN 10 PRECIO
--DISMINUIR EN 10 EL PRECIO

SELECT ProductName, UnitPrice, 
	UnitPrice + 10 AS SUMA, 
	UnitPrice -10 AS RESTA
FROM Products;

--CONSULTAR LA FECHA DE PEDIDO DE LA TABLA ORDERS 
--AUMENTAR EN 1 DIA LA FECHA DE PEDIDO
--DISMINUIR EN 5 DIAS LA FECHA DE PEDIDO

SELECT * FROM Orders

SELECT OrderDate,
	OrderDate +1 AS SUMA,
	OrderDate -5 AS RESTA
FROM Orders;


--MOSTRAR EL NOMBRE, PRECIO Y STOCK DE LOS PRODUCTOS 
--DISMINUIR EN 2 EL PRECIO DONDE EL STOCK SEA MAYOR 100

SELECT ProductName,UnitPrice,UnitsInStock,
       UnitPrice - 2 AS RESTA
FROM Products
WHERE UnitsInStock > 100;

--MOSTRAR EL NOMBRE, PRECIO Y STOCK DE LOS PRODUCTOS 
--AUMENTAR EN 15 EL PRECIO DONDE EL STOCK SEA MENOR 100

SELECT ProductName,UnitPrice,UnitsInStock,
       UnitPrice + 15 AS SUMA
FROM Products
WHERE UnitsInStock < 10;


--MULTIPLICAR Y DIVIDIR

--MOSTRAR EL NOMBRE, PRECIO Y STOCK DE LOS PRODUCTOS 
--CALCULAR EL COSTE DE INVENTARIO PRECIO POR STOCK

SELECT ProductName,UnitPrice,UnitsInStock,
       UnitPrice * UnitsInStock AS COSTE_INVENTARIO
FROM Products;

SELECT 10 / 2;
SELECT 21 / 2;

SELECT CAST(21 AS DECIMAL(7,2))/2

SELECT 0 / 0; --NO ES POSIBLE DIVIDIR ENTRE CERO

--MOSTRAR LA CANTIDAD, PRECIO Y STOCK DE LA TABLA ORDER DETAIL CALCULAR MONTO TOTAL CANTIDAD POR
--PRECIO MENOS EL DESCUENTO

SELECT * FROM [Order Details];


SELECT Quantity,UnitPrice, Discount,
       Quantity * (UnitPrice - (UnitPrice * Discount )) AS MONTOTOTAL
FROM [Order Details];

SELECT Quantity,UnitPrice, Discount,
       Quantity * UnitPrice - Discount AS MONTOTOTAL
FROM [Order Details];


--MODULO %

SELECT 10 % 5;

SELECT 10 % 3;